# Generated by Django 5.2.14 on 2026-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='target_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
    ]
