# Generated by Django 5.2.14 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_scrapejob_target_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoLocationCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("NOMINATIM", "OpenStreetMap Nominatim")],
                        db_index=True,
                        default="NOMINATIM",
                        max_length=32,
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("normalized_query", models.CharField(max_length=255)),
                ("country_code", models.CharField(blank=True, db_index=True, max_length=2)),
                ("is_hit", models.BooleanField(default=False)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("display_name", models.CharField(blank=True, max_length=512)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("raw_payload", models.JSONField(default=dict)),
                ("hits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Geo Location Cache",
                "verbose_name_plural": "Geo Location Cache",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(fields=["provider", "normalized_query", "country_code"], name="scraping_ge_provider_6ef8b8_idx"),
                    models.Index(fields=["last_used_at"], name="scraping_ge_last_us_18ec52_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="geolocationcache",
            constraint=models.UniqueConstraint(
                fields=("provider", "normalized_query", "country_code"),
                name="uniq_geo_cache_provider_query_country",
            ),
        ),
    ]
