# Generated by Django 6.0.5 on 2026-05-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_scrapejob_source_type'),
        ('scraping', '0003_geolocationcache'),
    ]

    operations = [
    ]
