# Generated by Django 6.0.5 on 2026-05-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0004_merge_20260530_2140"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="geolocationcache",
            new_name="scraping_ge_provide_a9b049_idx",
            old_name="scraping_ge_provider_6ef8b8_idx",
        ),
        migrations.RenameIndex(
            model_name="geolocationcache",
            new_name="scraping_ge_last_us_397181_idx",
            old_name="scraping_ge_last_us_18ec52_idx",
        ),
    ]
