# Generated by Django 6.0.5 on 2026-06-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0006_alter_scrapejob_source_type_windy"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapejob",
            name="offset_pages",
            field=models.IntegerField(
                default=0, help_text="Windy only: pagination offset (0=start, 1=1000-2000, etc)"
            ),
        ),
    ]
