# Generated by Django 6.0.5 on 2026-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0007_add_offset_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapejob",
            name="max_pages",
            field=models.IntegerField(
                default=20,
                help_text="Windy only: max pages to fetch (1-20, default 20 for ~1000 cameras)",
            ),
        ),
    ]
