# Generated by Django 6.0.5 on 2026-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_add_max_pages_to_scrapejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationcache',
            name='provider',
            field=models.CharField(choices=[('NOMINATIM', 'OpenStreetMap Nominatim'), ('IP_API', 'ip-api.com')], db_index=True, default='NOMINATIM', max_length=32),
        ),
        migrations.CreateModel(
            name='GeoIPCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('NOMINATIM', 'OpenStreetMap Nominatim'), ('IP_API', 'ip-api.com')], db_index=True, default='IP_API', max_length=32)),
                ('ip', models.GenericIPAddressField()),
                ('is_hit', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geo IP Cache',
                'verbose_name_plural': 'Geo IP Cache',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['provider', 'ip'], name='scraping_ge_provide_123c72_idx'), models.Index(fields=['provider', 'country_code'], name='scraping_ge_provide_028517_idx'), models.Index(fields=['last_used_at'], name='scraping_ge_last_us_380230_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'ip'), name='uniq_geo_ip_cache_provider_ip')],
            },
        ),
    ]
