# Generated by Django 5.2.14 on 2026-05-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('INSECAM', 'Insecam'), ('WHATSUPCAMS', 'WhatsUpCams')], db_index=True, max_length=20)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, max_length=1024)),
                ('preview_image', models.URLField(blank=True, max_length=1024)),
                ('page_url', models.URLField(blank=True, max_length=1024)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('has_partial_metadata', models.BooleanField(default=False)),
                ('source_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'is_online'], name='cameras_cam_source__500444_idx'), models.Index(fields=['country', 'city'], name='cameras_cam_country_182d4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CameraCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera Check Log',
                'verbose_name_plural': 'Camera Check Logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['camera', 'checked_at'], name='cameras_cam_camera__270697_idx')],
            },
        ),
    ]
