# Generated by Django 5.2.14 on 2026-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='camera',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='camera',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='camera',
            name='timezone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='camera',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['country_code', 'source_type'], name='cameras_cam_country_f337c6_idx'),
        ),
    ]
