# Generated by Django 5.2.14 on 2026-05-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapUISettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "disable_clustering_at_zoom",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="At or above this zoom level, clusters expand into individual markers.",
                        validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(18)],
                    ),
                ),
                (
                    "marker_limit",
                    models.PositiveIntegerField(
                        default=1500,
                        help_text="Maximum number of markers returned per map request.",
                        validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)],
                    ),
                ),
                (
                    "status_stale_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Status older than this many minutes is shown as stale.",
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)],
                    ),
                ),
                (
                    "popup_close_on_mouseout",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-close marker popup when pointer leaves marker.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Map UI Settings",
                "verbose_name_plural": "Map UI Settings",
            },
        ),
    ]
