# Generated by Django 5.2.14 on 2026-05-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_camera_country_code_camera_manufacturer_and_more"),
        ("cameras", "0002_mapuisettings"),
    ]

    operations = []
