# Generated by Django 6.0.5 on 2026-05-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_source_type'),
        ('cameras', '0003_merge_0002_camera_country_code_camera_manufacturer_and_more_0002_mapuisettings'),
    ]

    operations = [
    ]
