# Generated by Django 6.0.5 on 2026-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0007_go2rtc_grid_profiles"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="go2rtcconfigsnapshot",
            new_name="cameras_go2_instanc_be2e3e_idx",
            old_name="cameras_go2_instan_7f8f91_idx",
        ),
        migrations.RenameIndex(
            model_name="go2rtcgriditem",
            new_name="cameras_go2_profile_07b1e2_idx",
            old_name="cameras_go2_profile_950191_idx",
        ),
        migrations.RenameIndex(
            model_name="go2rtcgriditem",
            new_name="cameras_go2_instanc_6fd2fd_idx",
            old_name="cameras_go2_instan_4687b7_idx",
        ),
        migrations.RenameIndex(
            model_name="go2rtcinstance",
            new_name="cameras_go2_is_acti_b8fb3c_idx",
            old_name="cameras_go2_is_acti_8f6d2f_idx",
        ),
        migrations.RenameIndex(
            model_name="go2rtcstream",
            new_name="cameras_go2_instanc_e3d4ee_idx",
            old_name="cameras_go2_instan_191ab6_idx",
        ),
        migrations.RenameIndex(
            model_name="go2rtcstream",
            new_name="cameras_go2_instanc_0faa3b_idx",
            old_name="cameras_go2_instan_6f1942_idx",
        ),
        migrations.AddField(
            model_name="go2rtcinstance",
            name="group_label",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional logical grouping (e.g. a shared FQDN or site name). Instances with the same label are grouped together in the manager UI. Each instance still maps to a single go2rtc process on one host:port.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="go2rtcinstance",
            index=models.Index(
                fields=["is_active", "group_label", "name"], name="cameras_go2_is_acti_7a35e5_idx"
            ),
        ),
    ]
