# Generated by Django 6.0.5 on 2026-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cameras",
            "0008_rename_cameras_go2_instan_7f8f91_idx_cameras_go2_instanc_be2e3e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="go2rtcinstance",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Optional base path / subdirectory when go2rtc is served behind a reverse proxy (e.g. 'go2rtc' or 'app/go2rtc'). The resulting base URL becomes scheme://host:port/path.",
                max_length=255,
            ),
        ),
    ]
