# Generated by Django 6.0.5 on 2026-06-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0010_go2rtcinstance_resolved_ips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="go2rtcinstance",
            name="group_label",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional logical grouping (e.g. a shared FQDN or site name). Instances with the same label are grouped together in the manager UI. Each instance still maps to a single go2rtc process on one host:port. When set, this label overrides automatic IP-based grouping.",
                max_length=255,
            ),
        ),
    ]
