# Generated by Django 6.0.5 on 2026-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_alter_go2rtcinstance_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='geo_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='location_override_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, override location fields are used instead of auto GeoIP values.'),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go2rtcinstance',
            name='override_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='go2rtcinstance',
            index=models.Index(fields=['is_active', 'geo_country_code', 'name'], name='cameras_go2_is_acti_2bb662_idx'),
        ),
        migrations.AddIndex(
            model_name='go2rtcinstance',
            index=models.Index(fields=['is_active', 'override_country_code', 'name'], name='cameras_go2_is_acti_45d241_idx'),
        ),
    ]
