# Generated by Django 5.2.14 on 2026-05-26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMapSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "disable_clustering_at_zoom",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Override cluster expansion zoom level. Empty = global default.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(18)],
                    ),
                ),
                (
                    "marker_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override max markers per map request. Empty = global default.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)],
                    ),
                ),
                (
                    "status_stale_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override stale-status threshold in minutes. Empty = global default.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)],
                    ),
                ),
                (
                    "popup_close_on_mouseout",
                    models.BooleanField(
                        blank=True,
                        help_text="Override popup auto-close on mouseout. Empty = global default.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="map_settings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "User Map Settings",
                "verbose_name_plural": "User Map Settings",
            },
        ),
    ]
