# Generated by Django 5.2.14 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermapsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("hr", "Hrvatski")],
                db_index=True,
                default="en",
                help_text="Preferred interface language.",
                max_length=5,
            ),
        ),
    ]
