from __future__ import annotations

from typing import Any

from celery import Celery
from celery.schedules import crontab
from django.conf import settings

from apps.scraping.config import get_whatsupcams_country_codes

app = Celery("reconeye")

app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()


def _resolve_wuc_country_schedule(index: int, country_code: str) -> tuple[int, int]:
    """Resolve per-country WUC schedule (hour, minute).

    Priority:
    1) `PERIODIC_WUC_COUNTRY_CRON_OVERRIDES` setting (e.g. {"HR": "02:15"})
    2) fallback generated by base hour + minute step.
    """
    base_hour = int(getattr(settings, "PERIODIC_WUC_BASE_HOUR", 4))
    minute_step = max(1, int(getattr(settings, "PERIODIC_WUC_MINUTE_STEP", 5)))

    default_hour = (base_hour + (index // 12)) % 24
    default_minute = (index % 12) * minute_step

    overrides: dict[str, Any] = getattr(settings, "PERIODIC_WUC_COUNTRY_CRON_OVERRIDES", {}) or {}
    override = overrides.get(country_code.upper())
    if override is None:
        return default_hour, default_minute

    if isinstance(override, str):
        parts = override.split(":", 1)
        if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
            hour = int(parts[0]) % 24
            minute = int(parts[1]) % 60
            return hour, minute
        return default_hour, default_minute

    if isinstance(override, (list, tuple)) and len(override) == 2:
        try:
            hour = int(override[0]) % 24
            minute = int(override[1]) % 60
            return hour, minute
        except (TypeError, ValueError):
            return default_hour, default_minute

    return default_hour, default_minute

beat_schedule: dict[str, dict] = {
    # Camera status checks — every 15 minutes
    "refresh-camera-status": {
        "task": "reconeye.cameras.refresh_camera_status",
        "schedule": crontab(minute="*/15"),
    },
    # Maintenance
    "cleanup-old-logs-daily": {
        "task": "reconeye.cameras.cleanup_old_logs",
        "schedule": crontab(hour=2, minute=0),
    },
    # Cache warm-up after scrape runs
    "warm-cache-hourly": {
        "task": "reconeye.cameras.warm_cache",
        "schedule": crontab(minute=30),
    },
}


if getattr(settings, "ENABLE_PERIODIC_SCRAPING", False):
    beat_schedule.update(
        {
            # Scraping
            "scrape-insecam-daily": {
                "task": "reconeye.scraping.scrape_insecam",
                "schedule": crontab(hour=3, minute=0),
            },
        }
    )
    if not getattr(settings, "ENABLE_PERIODIC_WUC_BY_COUNTRY", False):
        beat_schedule["scrape-whatsupcams-daily"] = {
            "task": "reconeye.scraping.scrape_whatsupcams",
            "schedule": crontab(hour=4, minute=0),
        }

if getattr(settings, "ENABLE_PERIODIC_WUC_BY_COUNTRY", False):
    for index, country_code in enumerate(get_whatsupcams_country_codes()):
        hour, minute = _resolve_wuc_country_schedule(index, country_code)
        beat_schedule[f"scrape-whatsupcams-{country_code.lower()}-daily"] = {
            "task": "reconeye.scraping.scrape_whatsupcams",
            "schedule": crontab(hour=hour, minute=minute),
            "args": (country_code,),
        }

app.conf.beat_schedule = beat_schedule
