from __future__ import annotations

# Imported from OpenEyes wuc branch:
# https://github.com/mfabijanic/OpenEyes/tree/wuc
# Keep this file data-only so parser logic remains clean.

WUC_STREAM_PREFIX_OVERRIDES = {
    "do_buenhombre": "Buen Hombre",
    "es_lmarxx": "Lloret de Mar",
    "hr_baskavoda": "Baska Voda",
    "hr_blatozivogosce": "Blato Zivogosce",
    "hr_builddjakovo": "Dakovo",
    "hr_buildmurter": "Murter",
    "hr_buildfsb": "FSB, Zagreb",
    "hr_buildmurter": "Murter",
    "hr_buildnavitech": "Novi Vinodolski",
    "hr_buildngradiska": "Nova Gradiska",
    "hr_buildosijek": "Osijek",
    "hr_buildpaklenica": "Paklenica",
    "hr_buildpeljeskimost": "Peljeski most",
    "hr_buildpetrinja": "Petrinja",
    "hr_buildpula": "Pula",
    "hr_buildrab": "Rab",
    "hr_buildsamobor": "Samobor",
    "hr_buildsemeljci": "Semeljci",
    "hr_buildsibenik": "Sibenik",
    "hr_buildsljeme": "Sljeme",
    "hr_buildstrojarnica": "Strojarnica",
    "hr_buildsvhelena": "Sveta Helena",
    "hr_buildvarsavska": "Varsavska",
    "hr_buildzdencina": "Zdencina",
    "hr_cccres": "Cres",
    "hr_ccotocac": "Otocac",
    "hr_dive": "Dive",
    "hr_djakovo": "Dakovo",
    "hr_evecazma": "Cazma",
    "hr_evenovigrad": "Novigrad",
    "hr_everab": "Rab",
    "hr_golfadriatic": "Golf club Adriatic, Crveni Vrh",
    "hr_ivanjareka": "Ivanja Reka",
    "hr_korc": "Korcula",
    "hr_kuglanaporec": "Porec",
    "hr_kuglanazg": "Medveščak, Zagreb",
    "hr_lumbardares": "Lumbarda Resort",
    "hr_mdraga": "Moščenička Draga",
    "hr_mlosinj": "Mali Lošinj",
    "hr_monperin": "Mon Perin",
    "hr_nov": "Novigrad",
    "hr_novivinodolski": "Novi Vinodolski",
    "hr_pakos": "Pakoštane",
    "hr_ribotel": "Rijeka",
    "hr_senj": "Senj",
    "hr_splitbacvice": "Bacvice, Split",
    "hr_svfjakov": "Sveti Filip i Jakov",
    "hr_vgorica": "Velika Gorica",
    "hr_vlosinj": "Veli Lošinj",
    "hr_vluka": "Vela Luka",
    "hr_vranskojezero": "Vransko jezero",
    "hr_zagrebpetlja": "Petlja - ulaz, Zagreb",
    "hr_zgcamp": "Zagreb",
    "hr_zgjarun": "Jarun, Zagreb",
    "hr_zgparking": "Subiceva 40/III, 10000 Zagreb",
    "hr_zgvzpenjaca": "Uspinjaca, Zagreb",
    "hr_zgzoo": "Zoo, Zagreb",
    "it_bibionexx": "Bibione",
    "it_fornidisopra": "Forni di Sopra",
    "it_golfoaranci": "Golfo Aranci",
    "it_isolaverde": "Isola Verde",
    "it_lamaddalena": "La Maddalena",
    "it_livignoxx": "Livigno",
    "it_manerbagarda": "Manerba del Garda",
    "it_pratiditivo": "Prati di Tivo",
    "it_rosolinamare": "Rasolina Mare",
    "it_sangiovannisuergiu": "San Giovanni Suergiu",
    "it_santantioco": "Sant'Antioco",
    "it_santateresa": "Santa Teresa",
    "it_santeodoro": "San Teodoro",
    "it_sanvincenzo": "San Vincenzo",
    "it_tsborsa": "Borsa, TS",
    "it_udlignano": "Lignano, UD",
    "it_zonc": "Zoncolan",
    "mk_ohridxx": "Ohrid",
    "si_celjskoca": "Celjska Koča",
    "si_cerknobrdo": "Cerkno Brdo",
    "si_cezsoca": "Čezsoča",
    "si_crnikal": "Črni Kal",
    "si_gorenjavas": "Gorenja Vas",
    "si_hse_": "Koprska ulica 92, Ljubljana",
    "si_kocevje": "Kočevje",
    "si_kozjihrbet": "Kozji Hrbet",
    "si_kranjskagora": "Kranjska Gora",
    "si_ljgolf": "Golf, Ljubljana",
    "si_logmangart": "Log pod Mangartom",
    "si_mbpohorje": "Mariborsko Pohorje",
    "si_mostnasoci": "Most na Soci",
    "si_ngsk": "Nova Gorica",
    "si_pirantartini": "Piran Tartini",
    "si_polhovgradec": "Polhov Gradec",
    "si_solinesecovlje": "Secoveljske soline",
    "si_solkankajak": "Solkan Kajak",
    "si_starivrh": "Stari Vrh",
    "si_zoolj": "Zoo, Ljubljana",
    "si_zooljxx": "Zoo, Ljubljana",
    "test_554": "Zagreb, Hrvatska"
}

WUC_STREAM_LOCATION_OVERRIDES = {
    "do_buenhombre02": ["kite buen hombre kiteboarding school buen hombre beach", "La Costa De Buen Hombre"],
    "es_duquesa01": ["puerto de la duquesa marina", ""],
    "es_lmar1": ["lloret de mar the main beach costa brava spain", "Beach, Lloret de Mar"],
    "es_lmar2": ["lloret de mar dr doner costa brava spain", "Beach Doner Kebab, Lloret de Mar"],
    "es_roses01": ["live port of roses costa brava la perola beach", "Roses, Beach"],
    "es_roses02": ["port of roses costa brava spain", "Roses"],
    "es_roses04": ["roses costa brava beach view from montecarlo hotel", "Hotel Montecarlo, Roses"],
    "es_tenerife01": ["playa de las galgas playa paraiso costa adeje tenerife", "Las Galgas, Playa Paraiso"],
    "hr_bale01": ["bale view from soardo bembo palace istria", "Soardo-Bembo Palace, Castel, Bale, Istria"],
    "hr_baskavoda1": ["baska voda saint nikola and beach dalmatia", "Beach, Sveti Nikola, Baska voda"],
    "hr_baskavoda3": ["seaside promenade in baska voda dalmatia", "Baska voda"],
    "hr_baskavoda4": ["view of baska voda and biokovo mountain", "Baska voda"],
    "hr_baskavoda6": ["baska voda podluka beach", "Podluka, Baska voda"],
    "hr_brela02": ["općina brela", "Općina Brela"],
    "hr_brinje01": ["općina brinje", "Općina Brinje"],
    "hr_buildbrod02": ["slavonski brod", "Slavonski Brod"],
    "hr_buildbrod03": ["slavonski brod", "Slavonski Brod"],
    "hr_builddjakovo04": ["đakovo", "Đakovo"],
    "hr_buildkingc01": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkingc04": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkingc05": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkingc07": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkingc08": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkingcin06": ["king cross zagreb", "King Cross, Zagreb"],
    "hr_buildkrk01": ["krk", "Krk"],
    "hr_buildkrk02": ["krk", "Krk"],
    "hr_buildrovinj02": ["rovinj", "Rovinj"],
    "hr_buildtrogir01": ["trogir", "Trogir"],
    "hr_buildznjan02": ["znjan", "Žnjan, Split"],
    "hr_cazma01": ["čazma", "Čazma"],
    "hr_cclabin01": ["labin", "Labin"],
    "hr_cigoc01": ["grad sisak", "Grad Sisak"],
    "hr_cres01": ["cres city live main square and mandrac cres island", "Trg Arsan, Grad Cres"],
    "hr_crikvenica1": ["crikvenica stjepan radic square", "Crikvenica, Trg Stjepana Radića"],
    "hr_dive01": ["outdoor marine aquarium rogoznica", "Rogoznica, Marina"],
    "hr_drage03": ["drage", "Drage"],
    "hr_dubrovnik07": ["dubrovnik", "Dubrovnik"],
    "hr_djakovo01": ["đakovo", "Đakovo"],
    "hr_drvenik01": ["drvenik makarska dalmatia", "Drvenik"],
    "hr_drvenik02": ["drvenik dalmatia live in", "Drvenik"],
    "hr_evenovigrad01": ["grad novigrad", "Grad Novigrad"],
    "hr_everab02": ["town of rab", "Town of Rab"],
    "hr_fuzine01": ["fužine", "Fužine"],
    "hr_fuzine03": ["fužine", "Fužine"],
    "hr_fuzine04": ["fuzine toboggan run sanjkaliste", "Fuzine"],
    "hr_gajac1": ["gajac beach pag", "Gajac"],
    "hr_golfadriatic1": ["golf course adriatic savudrija", ""],
    "hr_golfadriatic2": ["golf adriatic live savudrija rezidencija skiper istria", "Adriatic, Savudrija"],
    "hr_igrane2": ["igrane marina dalmatia", "Igrane, Marina"],
    "hr_igrane3": ["igrane central beach", "Igrane, Beach"],
    "hr_japetic01": ["japetic jastrebarsko", ""],
    "hr_japetic02": ["plesivica jastrebarsko", ""],
    "hr_jelsa01": ["hvar island jelsa dalmatia", "Jelsa, Dalmatia"],
    "hr_jelsa04": ["jelsa hvar pjaca dalmatia", "Pjaca, Jelsa"],
    "hr_jelsa07": ["jelsa hvar panorama dalmatia", "Jelsa"],
    "hr_jelsadolac01": ["ivan dolac beach jelsa hvar dalmatia", "Beach, Ivan Dolac"],
    "hr_jelsazavala01": ["zavala jelsa hvar", "Zavala, Jelsa"],
    "hr_karlovac1": ["karlovac lana center and peter zrinski street", "Karlovac"],
    "hr_karlovac2": ["karlovac", "Karlovac"],
    "hr_karlovac3": ["karlovac outdoor swimming pool foginovo korana", "Pool bar, Karlovac"],
    "hr_klenovica1": ["klenovica", "Klenovica"],
    "hr_kolan01": ["municipality of kolan", "Municipality of Kolan"],
    "hr_korc3": ["korcula tri zala dalmatia", "Tri Zala, Grad Korcula"],
    "hr_korcula": ["korcula big revelin tower dalmatia", "Veliki Revelin, Grad Korcula"],
    "hr_krapina01": ["krapina", "Krapina"],
    "hr_krk02": ["krk", "Krk"],
    "hr_kuglanavbek1": ["kuglanavbek", "Kuglanavbek"],
    "hr_labin01": ["labin stari grad istria", "Labin, Stari grad"],
    "hr_makarska": ["makarska s seaside promenade", "Makarska"],
    "hr_makarska02": ["makarska", "Makarska"],
    "hr_makarskariva01": ["makarska riva king tomislav", "Riva, Obala kralja Tomislava, Makarska"],
    "hr_makarskariva02": ["makarska riviera", "Riva, Makarska"],
    "hr_mandre2": ["mandre", "Mandre"],
    "hr_mdraga01": ["moscenicka draga live istria", "Moscenicka draga"],
    "hr_mdraga02": ["moscenicka draga beach istra", "Beach, Moscenicka draga"],
    "hr_mdraga03": ["općina mošćenička draga", "Općina Mošćenička Draga"],
    "hr_medulin01": ["medulin riva istria", "Medulin"],
    "hr_medulin02": ["medulin live marina", "Medulin, Marina"],
    "hr_merag01": ["cres ferry port merag krk on cres island", "Luka Cres, Grad Cres"],
    "hr_mlosinj01": ["mali losinj riva losinjskih kapetana", ""],
    "hr_mlosinj02": ["mali lošinj", "Mali Lošinj"],
    "hr_mlosinj05": ["mali losinj lussinpiccolo main square", "Trg, Grad Mali Losinj"],
    "hr_monperin01": ["camping mon perin bale istria", "Camping Mon Perin, Bale, Istria"],
    "hr_monperin02": ["bale camping mon perin istria", "Camping Mon Perin, Bale, Istria"],
    "hr_monperin03": ["caming and mobile homes mon perin istria bale", "Camping Mon Perin, Bale, Istria"],
    "hr_mrkopalj02": ["općina mrkopalj", "Općina Mrkopalj"],
    "hr_mrkopalj03": ["općina mrkopalj", "Općina Mrkopalj"],
    "hr_nov2": ["seaside promenade in novalja pag", "Pag, Novalja"],
    "hr_nov5": ["grad novigrad", "Grad Novigrad"],
    "hr_nov6": ["grad novigrad", "Grad Novigrad"],
    "hr_nov7": ["grad novigrad", "Grad Novigrad"],
    "hr_nov8": ["grad novigrad", "Grad Novigrad"],
    "hr_novalja": ["grad novalja", "Grad Novalja"],
    "hr_novigrad2": ["live novigrad veliki trg istria", "Grad Novigrad, Veliki trg"],
    "hr_novigrad3": ["novigrad porporela istria", "Grad Novigrad, Porporela"],
    "hr_novigrad4": ["grad novigrad", "Grad Novigrad"],
    "hr_novivinodolski1": ["novi vinodolski main street hrvatskih branitelja", "Korzo hrvatskih branitelja, Grad Novi Vinodolski"],
    "hr_novivinodolski2": ["novi vinodolski harbour", "Luka Krmpotska, Grad Novi Vinodolski"],
    "hr_novivinodolski3": ["novi vinodolski beach live", "Beach, Grad Novi Vinodolski"],
    "hr_novivinodolski4": ["novi vinodolski", "Novi Vinodolski"],
    "hr_ogulin01": ["ogulin center", "Grad Ogulin"],
    "hr_ogulin04": ["ogulin panorama", "Ogulin"],
    "hr_opatija01": ["opatija panorama from the hotel milenij", "Hotel Milenij, Opatija"],
    "hr_opuzen1": ["neretva kite center kiteboarding opuzen", "Neretva, Opuzen"],
    "hr_otocac01": ["otočac", "Otočac"],
    "hr_otocac02": ["otočac", "Otočac"],
    "hr_otok01": ["općina otok", "Općina Otok"],
    "hr_pag01": ["most katine pag", "Pag"],
    "hr_pag02": ["pag main square and church of st mary", "Pag"],
    "hr_pag03": ["pag town marina pag", "Luka Pag"],
    "hr_pag04": ["pag beach pag", "Pag"],
    "hr_pakos1": ["općina pakoštane", "Općina Pakoštane"],
    "hr_pakos4": ["općina pakoštane", "Općina Pakoštane"],
    "hr_planjka": ["planjka beach novalja pag island", "Pag"],
    "hr_pirovac01": ["općina pirovac", "Općina Pirovac"],
    "hr_ploce01": ["grad ploče", "Grad Ploče"],
    "hr_podgora2": ["podgora beach dalmatia", "Beach Podgora, Dalmatia"],
    "hr_podgora4": ["podgora marina", "Marina Podgora, Dalmatia"],
    "hr_povile01": ["povile beach novi vinodolski", "Grad Novi Vinodolski, Povile"],
    "hr_povljana01": ["povljana pag island", "Povljana"],
    "hr_povljana02": ["municipality of povljana", "Municipality of Povljana"],
    "hr_promajna01": ["promajna beach live dalmatia", "Promajna, Općina Baška Voda"],
    "hr_pula01": ["pula korzo giardini", "Pula, Giardini"],
    "hr_pula03": ["amphitheatre in pula arena", "Arena, Pula"],
    "hr_pula04": ["pula arena forum and the tample of augustus", "Arena, Pula"],
    "hr_pula06": ["pula koper street live cam istria", "Pula"],
    "hr_rakovica01": ["rakovica", "Rakovica"],
    "hr_rekajadranskitrg": ["rijeka jadran square", "Rijeka, Jadranski trg"],
    "hr_ribotel01": ["botel marina rijeka live cam", "Rijeka, Botel Marina"],
    "hr_rijeka02": ["rijeka korzo reka", "Rijeka, Korzo"],
    "hr_rijeka03": ["reka city tower and clock rijeka", "Rijeka, City tower"],
    "hr_rijeka04": ["rijeka the view of trsat and susak", "Rijeka"],
    "hr_rijeka05": ["rijeka rjecina fiumara and tito square", "Rijeka, Rjecina"],
    "hr_rijeka08": ["rijeka beach swimming pools kantrida", "Rijeka, Kantrida"],
    "hr_rijeka09": ["the riva and marina in rijeka live", "Rijeka, Riva"],
    "hr_rogoznica01": ["rogoznica seashore kneza domagoja", "Rogoznica, Obala kneza Domagoja"],
    "hr_rovenska01": ["rovenska veli losinj", "Veli Losinj, Rovenska"],
    "hr_rovinj2": ["rovinj panorama of city istria", "Rovinj"],
    "hr_rovinj3": ["rovinj live cam the main square", "Rovinj, Trg"],
    "hr_samobor1": ["grad samobor", "Grad Samobor"],
    "hr_samobor2": ["samobor main square", "Samobor - Main Square"],
    "hr_selce1": ["selce beach diving center", "Selce"],
    "hr_senj01": ["senj nehaj fortress kvarner", "Senj"],
    "hr_senj02": ["senj harbor kvarner croatia", "Senj"],
    "hr_senj05": ["grad buzet", "Grad Buzet"],
    "hr_simuni": ["camping simuni pag", "Camping Simuni, Pag"],
    "hr_sibenik02": ["grad šibenik", "Grad Šibenik"],
    "hr_sibenik03": ["grad šibenik", "Grad Šibenik"],
    "hr_silba02": ["silba", "Silba"],
    "hr_sisak02": ["grad sisak", "Grad Sisak"],
    "hr_skrad01": ["skrad", "Skrad"],
    "hr_slano01": ["slano", "Slano"],
    "hr_sljeme3": ["općina stubičke toplice", "Općina Stubičke Toplice"],
    "hr_split": ["split seaside promenade", "Split"],
    "hr_split04": ["split view of split riva", "Riva, Split"],
    "hr_splitbacvice01": ["bacvice beach split webcam", "Bacvice beach, Split"],
    "hr_sutivan02": ["općina sutivan", "Općina Sutivan"],
    "hr_svfjakov01": ["općina sveti filip i jakov", "Općina Sveti Filip i Jakov"],
    "hr_tkon01": ["općina tkon", "Općina Tkon"],
    "hr_tkon02": ["općina tkon", "Općina Tkon"],
    "hr_tkon04": ["općina tkon", "Općina Tkon"],
    "hr_tkon05": ["tkon kalvaria view of pasman channel", "Tkon"],
    "hr_tkon06": ["općina tkon", "Općina Tkon"],
    "hr_tkon07": ["tkon live cam ferry dalmatia", "Luka Tkon"],
    "hr_tkon08": ["dalmatia tkon ferry", "Luka Tkon"],
    "hr_trakoscan01": ["trakošćan", "Trakošćan"],
    "hr_trakoscan02": ["trakošćan", "Trakošćan"],
    "hr_trsat01": ["shrine of our lady of trsat rijeka", "Rijeka, Trsat"],
    "hr_ugljan01": ["ugljan ferry", "Luka Ugljan"],
    "hr_umag3": ["umag town center", "Umag"],
    "hr_umag5": ["umag hotel zlatna vala", "Duba, Umag"],
    "hr_umag6": ["umag", "Umag"],
    "hr_umag7": ["umag live lovrecica san lorenzo istria", "Umag, Lovrecica - San Lorenzo"],
    "hr_unije03": ["unije island in", "Unije, Grad Mali Losinj"],
    "hr_vgorica01": ["city of velika gorica", "City of Velika Gorica"],
    "hr_viganj1": ["viganj windsurf beach dalmatia", "Beach, Viganj"],
    "hr_viganj2": ["viganj", "Viganj"],
    "hr_viganj3": ["viganj peljesac view from antony boy autocamp", "Viganj"],
    "hr_viganj4": ["viganj", "Viganj"],
    "hr_vir1": ["vir sv jurja square dalmatia", "Vir"],
    "hr_vir2": ["vir live beach dalmatia", "Vir"],
    "hr_visnjan01": ["visnjan observatory in", "Observatory, Visnjan"],
    "hr_visnjan02": ["visnjan observatory", "Observatory, Visnjan"],
    "hr_vlosinj05": ["veli lošinj", "Veli Lošinj"],
    "hr_vodice3": ["grad vodice", "Grad Vodice"],
    "hr_vodice4": ["grad vodice", "Grad Vodice"],
    "hr_vrboska01": ["vrboska island of hvar dalmatia", "Vrboska"],
    "hr_vranskojezero": ["vransko jezero", "Vransko jezero"],
    "hr_zadar2": ["zadar bridge", "Zadar"],
    "hr_zadar3": ["zadar trg petra zoranica", "Trg Petra Zoranica, Zadar"],
    "hr_zadar4": ["zadar", "Zadar"],
    "hr_zagreb5": ["city of zagreb", "City of Zagreb"],
    "hr_zagreb7": ["city of zagreb", "City of Zagreb"],
    "hr_zagrebpetlja": ["petlja - ulaz, zagreb", "Petlja - ulaz, Zagreb"],
    "hr_zgcamp": ["zagreb", "Zagreb"],
    "hr_zgjarun": ["jarun, zagreb", "Jarun, Zagreb"],
    "hr_zgparking": ["subiceva 40/iii, 10000 zagreb", "Subiceva 40/III, 10000 Zagreb"],
    "hr_zgvzpenjaca": ["uspinjaca, zagreb", "Uspinjaca, Zagreb"],
    "hr_zgzoo": ["zoo, zagreb", "Zoo, Zagreb"],
    "hr_zgzoo01": ["city of zagreb", "City of Zagreb"],
    "hr_zrce1": ["zrce wakeboard live cam pag island", "Zrce, Novalja"],
    "it_agultu01": ["la marinedda isola rossa agultu sardinia italy", ""],
    "it_agultu02": ["isola rossa beach live view of sardegna", "Isola Rossa"],
    "it_alghero02": ["maia pia beach alghero sardinia italy", "Alghero Sardinia"],
    "it_alghero03": ["", "Alghero Sardinia"],
    "it_alghero05": ["spiaggia poglina da ricciolina", "Alghero Sardinia"],
    "it_arzachena01": ["phi beach forte cappellini porto cervo", "Phi Beach Club, Via Forte Cappellini"],
    "it_arzachena05": ["spiaggia del pevero arzachena costa smeralda sardegna", "Smeralda Sardegna"],
    "it_bibione12": ["villaggio mare blu pool bibione pineda", "Villaggio Mare Blu, Bibione"],
    "it_bibione13": ["beach villaggio mare blu pool bibione pineda", "Villaggio Mare Blu, Bibione"],
    "it_bibionexx": ["bibione", "Bibione"],
    "it_bosa01": ["live bosa marina sardinia italy", "Bosa Marina, Sardinia"],
    "it_buggerru02": ["beach san nicolo buggerru sardinia", ""],
    "it_cagliari01": ["cagliari", "Cagliari"],
    "it_capoterra01": ["capoterra la maddalena beach sardinia italy", "Capoterra - La Maddalena"],
    "it_cardedu01": ["museddu beach ogliastra sardinia italy", "Museddu, Cardedu, Ogliastra, Sardinia"],
    "it_castelsardo02": ["lu bagnu ampurias beach castelsardo sardinia italy", "Lu Bagnu, Castelsardo, Sardinia"],
    "it_cuglieri01": ["sarchittu beaches in sardinia", "Sardinia"],
    "it_fornidisopra01": ["forni di sopra / for disora", "Forni di Sopra / For Disora"],
    "it_golfoaranci01": ["spiaggia cala sassari golfo aranci", ""],
    "it_isolaverde": ["isola verde", "Isola Verde"],
    "it_lamaddalena01": ["ponte caprera la maddalena sardinia italy", ""],
    "it_lamaddalena02": ["the boat lo squalo iv arcipelago la maddalena sardinia italy", "Arcipelago di La Maddalena, Sardinia"],
    "it_livigno02": ["panorama of ski destination livigno italy", "Livigno"],
    "it_livigno05": ["livigno", "Livigno"],
    "it_livignoxx": ["livigno", "Livigno"],
    "it_manerbagarda": ["manerba del garda", "Manerba del Garda"],
    "it_olbia03": ["marinella beach porto rotondo olbia sardinia", "Marinella, Olbia, Sardinia"],
    "it_olbia05": ["porto di olbia", "Porto Rotondo, Olbia"],
    "it_palau01": ["lu palau/palau", "Lu Palau/Palau"],
    "it_palau02": ["porto pollo beach sardinia hotel le dune", "Hotel Le Dune, Via Tramontana, Sardinia"],
    "it_palau05": ["isuledda porto pollo isola dei gabbiani", "Porto Pollo, Sardinia"],
    "it_palau09": ["porto pollo windsurfing and kite surfing live sardinia italy", "Porto Pollo, Sardinia"],
    "it_posada01": ["posada beach sardinia italy", "Posada, Sardinia"],
    "it_pratiditivo": ["prati di tivo", "Prati di Tivo"],
    "it_riccione01": ["riccione beach bagni oreste", "Oreste"],
    "it_riccione03": ["riccione zona 3 riccione beach webcam", "Riccione Beach"],
    "it_rosolinamare01": ["holiday village rosapineta sud webcam", "Rosolina Mare"],
    "it_rosolinamare02": ["camping vittoria rosolina mare", "Rosolina Mare"],
    "it_rosolinamare03": ["rosolina mare city center", "Rosolina Mare"],
    "it_rosolinamare04": ["bagno primavera beach rosolina mare webcam", "Rosolina Mare"],
    "it_rosolinamare": ["rasolina mare", "Rasolina Mare"],
    "it_sangiovannisuergiu01": ["punta trettu san giovanni suergiu sardinia", ""],
    "it_sangiovannisuergiu": ["san giovanni suergiu", "San Giovanni Suergiu"],
    "it_santantioco": ["sant'antioco", "Sant'Antioco"],
    "it_santateresa02": ["la liccia beach rena majore santa teresa gallura sardinia", "La Liccia Rena Majori, Santa Teresa Gallura"],
    "it_santateresa": ["santa teresa", "Santa Teresa"],
    "it_santeodoro02": ["san teodoro spiaggia lu impostu sardegna", "Spiaggia lu Impostu, San Teodoro, Sardinia"],
    "it_santeodoro": ["san teodoro", "San Teodoro"],
    "it_sanvincenzo": ["san vincenzo", "San Vincenzo"],
    "it_sorso02": ["marina di sorso lido di sorso beach sardinia", "Marina Di Sorso, Sardinia"],
    "it_sperlonga01": ["sperlonga", ""],
    "it_stintino03": ["stintino live la pelosa beach sardinia italy", "Stintino la Pelosa, Sardinia"],
    "it_talamone01": ["talamone spectacular view of the rocca aldobrandesca", "Rocca Aldobrandesca, Talamone"],
    "it_talamone05": ["talamone live wind beach tuscany italy", "Talamone, Toscana"],
    "it_tsborsa": ["borsa, ts", "Borsa, TS"],
    "it_udlignano": ["lignano, ud", "Lignano, UD"],
    "it_valledoria01": ["la ciaccia valledoria sardinia italy", "La Ciaccia, Valledoria, Sardinia"],
    "it_valledoria02": ["valledoria live san pietro beach sardinia italy", "International Camping Valledoria, Pineta San Pietro, Valledoria, Sardinia"],
    "it_zonc": ["zoncolan", "Zoncolan"],
    "mk_ohridxx": ["ohrid", "Ohrid"],
    "si_bovec": ["bovec", "Bovec"],
    "si_bovec02": ["bovec airport", "Bovec, Airport"],
    "si_brda01": ["smartno brda hotel san martin", "Smartno, Brda"],
    "si_celjskoca01": ["celjska koca view from hotel celje", "Celjska Koca, Hotel Celje"],
    "si_celjskoca02": ["celjska koca celje", "Celjska Koca, Celje"],
    "si_cerje01": ["cerje miren kostanjevica", "Cerje, Miren-Kostanjevica"],
    "si_cerkno01": ["live kmetija na lanisah cerkno", "Cerkno"],
    "si_dandi01": ["rogla apartments dandi jurgovo", "Rogla"],
    "si_kobarid01": ["kobarid view to kobariski stol", "Kobarid"],
    "si_kobarid03": ["kobarid city center soca valley", "Kobarid"],
    "si_kobarid04": ["krn planina kuhinja kobarid", "Planina Kuhinja - Krn, Kobarid"],
    "si_kobarid05": ["charnel house kobarid", "Charnel house, Kobarid"],
    "si_koper04": ["koper panorama marina and promenade grand hotel koper", "Koper, Hotel Koper"],
    "si_kranjskagora2": ["rtc kranjska gora ski run mojca rozle", "Rozle, Kranjska Gora"],
    "si_kranjskagora3": ["kranjska gora beach", "Kranjska Gora"],
    "si_kranjskagora9": ["ski kranjska gora vitranc", "Vitranc, Kranjska Gora"],
    "si_krvavec2": ["krvavec ski center funicular station", "Krvavec"],
    "si_ljgolf": ["golf country klub ljubljana smlednik", "Ljubljana, Smlednik"],
    "si_ljpz1": ["portoroz airport ljpz", "Portoroz, Airport"],
    "si_ljzoo1": ["zoo ljubljana giraffes", "Ljubljana, Zoo"],
    "si_ljzoo10": ["lion live in ljubljana zoo", "Ljubljana, Zoo"],
    "si_ljzoo5": ["bird feeders at zoo ljubljana", "Ljubljana, Zoo"],
    "si_mbpohorje02": ["maribor pohorje arena", "Mariborsko Pohorje"],
    "si_mbpohorje05": ["maribor pohorje ski resort trikotna jasa", "Mariborsko Pohorje"],
    "si_mbpohorje10": ["maribor pohorje bellevue", "Mariborsko Pohorje"],
    "si_ngbevkovtrg": ["bevkov trg nova gorica", "Bevkov trg, Nova Gorica"],
    "si_ngorica03": ["nova gorica edvard kardelj square", "Nova Gorica"],
    "si_ngsk": ["nova gorica", "Nova Gorica"],
    "si_ngsk1": ["skate park nova gorica live", "Nova Gorica"],
    "si_ngsk3": ["skate park nova gorica", "Nova Gorica"],
    "si_ngsp02": ["live tennis club in nova gorica", "Nova Gorica"],
    "si_otocec01": ["golf otocec webcam", "Otocec"],
    "si_piran05": ["villa piranesi live view piran", "Piran"],
    "si_piran06": ["from piran mandrac villa piranesi", "Piran"],
    "si_pirantartini": ["piran tartini square", "Piran"],
    "si_polhovgradec": ["polhov gradec", "Polhov Gradec"],
    "si_predjama01": ["predjamski grad predjama castle postojna", "Predjamski grad, Predjama, Postojna"],
    "si_solkan02": ["soca river solkan bicycle bridge", "Soca, Solkan"],
    "si_solkankajak": ["soca river at solkan kayak center", "Soca, Solkan"],
    "si_sorica02": ["sorica ski resort soriska planina vrh lajnar", "Soriska planina"],
    "si_starivrh": ["stari vrh", "Stari Vrh"],
    "si_velikaplanina02": ["velika planina", "Velika Planina"],
    "si_vogel1": ["ski resort vogel", "Vogel"],
    "si_vogel3": ["vogel ski resort view from orlova glava to triglav", "Vogel"],
    "si_vogel4": ["bohinj lake and triglav view from vogel ski resort", "Vogel"],
    "si_vrsic01": ["vrsic erjavceva koca view to prisojnik", "Vrsic"],
    "si_vrsic02": ["vrsic erjavceva house", "Vrsic"],
    "si_zoolj": ["zoo, ljubljana", "Zoo, Ljubljana"],
    "si_zoolj11": ["zebras in ljubljana zoo", "Ljubljana Zoo"],
    "si_zooljxx": ["zoo, ljubljana", "Zoo, Ljubljana"],
    "test_554": ["zagreb, hrvatska", "Zagreb, Hrvatska"]
}
